### ISSUE TITLE
Python3 version

### ISSUE THREAD

**Issue by satreix** [codeinn/vcs#121]
Would it be possible to move your tool over to python3 ? I'm willing to help. :smile:

**Comment by eirnym** [comment]
There's only 2 years left to deadline

**Comment by satreix** [comment]
@marcinkuzminski @lukaszb are you still working on this? How can I help make it happen?

Note: I think we are passed the deadline.

**Comment by eirnym** [comment]
I bet authors are not aware about mercurial 5.x which support Python3

**Comment by lukaszb** [comment]
We are, however we have stopped working on this project long time ago. If you want to help, PRs are always welcomed.

**Comment by marcinkuzminski** [comment]
Hi there.

I don't think this will ever happen. We're not working on this library as a standalone lib anymore. 

Please note that Mercurial supporting python3 is just a small piece of whole migration, as Dulwich probably needs to be replaced by libgit2 etc. Migrating to python3 at the current state means rewriting this library in a major way.

**Comment by eirnym** [comment]
Dulwich is officially supports Python 3.6 to 3.8 based on information from [official repository](https://github.com/dulwich/dulwich)

**Comment by eirnym** [comment]
up to 38 but not limited by it as well

**Comment by satreix** [comment]
@lukaszb @marcinkuzminski  I read "PR welcomed" and I read "this will not happen"; you know this library better than, can you list the blocker you see to a working Py3 version?

Another question is what should we aim for, a p2-py3 version with six like abstraction layers, or given we are past the python2 support date do we want to jump all in in py3?

Thanks for your time.
