### ISSUE TITLE
travis fails on mercurial version

### ISSUE THREAD

**Issue by stardust85** [codeinn/vcs#124]
2.5.2 doesn't exist, we should change it at least to 2.6.2 in the requirements

**Comment by stardust85** [comment]
https://travis-ci.org/codeinn/vcs/jobs/100873923

**Comment by marcinkuzminski** [comment]
argh, how can you remove a dependency :/ i'm not sure if there are no API changes between 2.6.2 and 2.5.2, maybe we use a fallback url that exposes 2.5.2

https://www.mercurial-scm.org/release/mercurial-2.5.2.tar.gz

**Comment by stardust85** [comment]
I wouldn't be so prudent. If the tests pass, it should be ok :) But unability to run travis kills motivation for contributions which can kill the project itself. So we have nothing to lose, do we?

**Comment by marcinkuzminski** [comment]
I actually checked in our internal code when we bumped it to Mercurial 2.6.X and there were no API changes required.

**Comment by marcinkuzminski** [comment]
I made a small PR #126

**Comment by marcinkuzminski** [comment]
Also one comment, we need to pin dulwich as well, there were too many breaking changes in latest release (unicode related etc)

**Comment by stardust85** [comment]
I pinned dulwich in my branch 'travis-fix' to 0.10.0 and only 2 tests fail for me :)

**Comment by marcinkuzminski** [comment]
I think we need to pin it to 0.9.1 that was the version available at last commit.
